
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Ship_task/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

//jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Ship Task<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Ship Task</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('ship_task_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Ship Task']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/ship_task/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Ship Task']); ?></a>
                        <?php }) ?>
                       <!--  <?php is_allowed('ship_task_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Ship Task" href="<?= site_url('administrator/ship_task/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('ship_task_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Ship Task" href="<?= site_url('administrator/ship_task/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?> -->
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Ship Task</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Ship Task']); ?>  <i class="label bg-yellow"><?= $ship_task_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_ship_task" id="form_ship_task" action="<?= base_url('administrator/ship_task/index'); ?>">
                  
                     
                  <div class="table-responsive"> 
                  <table class="table table-responsive table-bordered table-striped dataTable">
                      <thead >
                        <tr class="danger">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Company</th>
                           <th>Ship Name</th>
                           <th>Order Number</th>
                           <th>Scope Type</th>
                           <th>Equipment</th>
                           <th>Sparepart</th>
                           <!--<th>Schedule</th>-->
                           <th>Status</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_ship_task">
                     <?php foreach($ship_tasks as $ship_task): ?>
                         <tr class="success">
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $ship_task->ship_name; ?>">
                           </td>
                           
                           <td><?= _ent($ship_task->name); ?></td>
                             
                           <td><?= _ent($ship_task->ship_name); ?></td>
                             
                           <td><?= _ent($ship_task->order_number); ?></td> 
                           <td><?= _ent($ship_task->scope_type); ?></td> 
                           <td>
                                 
                                    <?php  $scope_type = $ship_task->scope_type ; 
                                           $array = explode(",",$scope_type);  ?>
                               
                                       <?php foreach ($array as $value) : ?>
                                         <?php if($value == 'Installation'): ?>
                                            <a
                                               href="<?= site_url('administrator/task_equipment/ap/' . $ship_task->order_number); ?>"
                                               class="btn btn-info btn-block"><i class="fa fa-plus-square"></i>
                                               Add New Equipment</a>    
                                            <?php break; ?>        
                                    
                                        <?php endif; ?>
                                                
                                    <?php endforeach; ?> 
                                     
                           </td>
                           
                            <td>
                                 
                                    <?php  $scope_type = $ship_task->scope_type ; 
                                           $array = explode(",",$scope_type);  ?>
                               
                                       <?php foreach ($array as $value) : ?>
                                         <?php if($value == 'Repair / General Checking'): ?>
                                            <a
                                               href="<?= site_url('administrator/task_sparepart/ap/' . $ship_task->order_number); ?>/1"
                                               class="btn btn-warning btn-block"><i class="fa fa-plus-square"></i>
                                               Add New Sparepart</a>    
                                            <?php break; ?>        
                                    
                                        <?php endif; ?>
                                                
                                    <?php endforeach; ?> 
                                     
                           </td>
                           
                           
<!--                           <td><?= _ent($ship_task->schedule); ?></td> -->
                           <td><?= _ent($ship_task->job_status); ?></td> 
                           <td>
                              <?php is_allowed('ship_task_view', function() use ($ship_task){?>
                              <a href="<?= site_url('administrator/ship_task/view/'.$ship_task->id_task); ?>" class="btn btn-info btn-block"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                               
                                  <a href="<?= site_url('administrator/ship_task/printInvoice/'.$ship_task->order_number); ?>"class="btn btn-success btn-block" target="_blank" ><i class="fa fa-file-pdf-o"></i>&nbsp;&nbsp;Invoice</a>
                              
                              <a href="<?= site_url('administrator/ship_task/printDuty/'.$ship_task->order_number); ?>" class="btn btn-warning btn-block" target="_blank"><i class="fa fa-file-pdf-o  "></i>&nbsp;&nbsp;Letter of Duty</a>
                               
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($ship_task_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Ship Task data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
                
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'company' ? 'selected' :''; ?> value="company">Company</option>
                           <option <?= $this->input->get('f') == 'ship_name' ? 'selected' :''; ?> value="ship_name">Ship Name</option>
                           <option <?= $this->input->get('f') == 'order_number' ? 'selected' :''; ?> value="order_number">Order Number</option>
                           <option <?= $this->input->get('f') == 'schedule' ? 'selected' :''; ?> value="schedule">Schedule</option>
                           <option <?= $this->input->get('f') == 'status' ? 'selected' :''; ?> value="status">Status</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/ship_task');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_ship_task').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/ship_task/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>