<html>
     <style type="text/css">
        .col-sm-8 {
          margin-left: 70px;  
          padding-top: 5px;
          background-color:#e3e3e3;
        }
    </style>
   
</html>

<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


//jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Ship Task      <small><?= cclang('detail', ['Ship Task']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/ship_task'); ?>">Ship Task</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Ship Task</h3>
                     <h5 class="widget-user-desc">Detail Ship Task</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_ship_task" id="form_ship_task" >
                   
<!--                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Task </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->id_task); ?>
                        </div>
                    </div>-->
                     <div class="message" id="message_installation" >
                            <div class="callout callout-info btn-flat ">
                                <b># General Info</b>
                            </div>
                        </div>                     
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Company </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ship Name </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->ship_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Number </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->order_number); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Schedule </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->schedule); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Location </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->location); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Scope Type </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->scope_type); ?>
                        </div>
                    </div>
                    
                     <div class="message" id="message_installation" >
                            <div class="callout callout-info btn-flat ">
                                <b># Survey</b>
                            </div>
                        </div>    

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Survey Type </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->survey_type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Engineer Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->survey_engineer_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ticket Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->survey_ticket_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Transport Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->survey_transport_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Speedboat Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->survey_speedboat_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Daily Allowance Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->survey_dailyallowance_fee); ?>
                        </div>
                    </div>
                    
                    <div class="message" id="message_installation" >
                                               <div class="callout callout-info btn-flat ">
                                                   <b># Installation</b>
                                               </div>
                                           </div>    

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Installation </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->installation); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Logistic Equipment </label>

                        <div class="col-sm-8">
                            <div class="table-responsive"> 
                                <table class="table table-responsive table-bordered table-striped dataTable">
                                    <thead>
                                        <tr class="danger">
                                              <th>Equipment Name</th>
                                              <th>Equipment Type</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            <?php foreach (db_get_data_equipment_by_order_number('task_equipment',$ship_task->order_number) as $row): ?>
                                               <tr class="success"> 
                                                <td><?= $row->task_equipment_name; ?></td>
                                                <td><?= $row->task_equipment_type; ?></td>
                                               </tr> 
                                            <?php endforeach; ?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Engineer Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->installation_engineer_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ticket Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->installation_ticket_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Transport Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->installation_transport_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Speedboat Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->installation_speedboat_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Daily Allowance Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->installation_dailyallowance_fee); ?>
                        </div>
                    </div>
                    
                     <div class="message" id="message_installation" >
                            <div class="callout callout-info btn-flat ">
                                <b># Repair / General Checking</b>
                            </div>
                        </div>    
                    
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Repair </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->repair); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Logistic Sparepart </label>

                        <div class="col-sm-8">
                            <div class="table-responsive"> 
                                <table class="table table-responsive table-bordered table-striped dataTable">
                                    <thead>
                                        <tr class="danger">
                                              <th>Sparepart Name</th>
                                              <th>Sparepart Type</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            <?php foreach (db_get_data_sparepart_by_order_number('task_sparepart',$ship_task->order_number) as $row): ?>
                                               <tr class="success"> 
                                                <td><?= $row->task_sparepart_name; ?></td>
                                                <td><?= $row->task_sparepart_type; ?></td>
                                               </tr> 
                                            <?php endforeach; ?>

                                    </tbody>
                                </table>
                            </div>
                    </div>
                   </div>                     
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Engineer Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->repair_engineer_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ticket Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->repair_ticket_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Transport Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->repair_transport_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Speedboat Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->repair_speedboat_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Daily Allowance Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->repair_dailyallowance_fee); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Notes </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->notes); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Engineer </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_task->engineer); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('ship_task_update', function() use ($ship_task){?>
                        <!--<a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit ship_task (Ctrl+e)" href="<?= site_url('administrator/ship_task/edit/'.$ship_task->ship_name); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Ship Task']); ?> </a>-->
                        <?php }) ?>
                        <a class="btn btn-flat btn-warning btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/ship_task/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Ship Task']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
