
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Logistic_equipment/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<!--<section class="content-header">
   <h1>
      Logistic Equipment<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Logistic Equipment</li>
   </ol>
</section>-->
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
<!--                     <div class="row pull-right">
                        <?php is_allowed('logistic_equipment_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Logistic Equipment']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/logistic_equipment/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Logistic Equipment']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('logistic_equipment_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Logistic Equipment" href="<?= site_url('administrator/logistic_equipment/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('logistic_equipment_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Logistic Equipment" href="<?= site_url('administrator/logistic_equipment/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>-->
<!--                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                      /.widget-user-image 
                     <h3 class="widget-user-username">Logistic Equipment</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Logistic Equipment']); ?>  <i class="label bg-yellow"><?= $logistic_equipment_counts; ?>  <?= cclang('items'); ?></i></h5>-->
                  </div>

                  <form name="form_logistic_equipment" id="form_logistic_equipment" action="<?= base_url('administrator/Ship_task_equipment/index'); ?>">
                  
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
<!--                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>-->
<!--                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>-->
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'logistic_equipment_name' ? 'selected' :''; ?> value="logistic_equipment_name">Logistic Equipment Name</option>
                           <option <?= $this->input->get('f') == 'logistic_maker' ? 'selected' :''; ?> value="logistic_maker">Logistic Maker</option>
                           <option <?= $this->input->get('f') == 'logistic_equipment_type' ? 'selected' :''; ?> value="logistic_equipment_type">Logistic Equipment Type</option>
                           <option <?= $this->input->get('f') == 'logistic_serial_number' ? 'selected' :''; ?> value="logistic_serial_number">Logistic Serial Number</option>
                           <option <?= $this->input->get('f') == 'quantity' ? 'selected' :''; ?> value="quantity">Quantity</option>
                           <option <?= $this->input->get('f') == 'price' ? 'selected' :''; ?> value="price">Price</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/logistic_equipment');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>      
               <div class="table-responsive"> 
                   <table id="dt_equipment"  class="table table-bordered table-striped dataTable">
                       <thead>
                           <tr class="">
                               <th>
                                   <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                               </th>
                               <th>Name</th>
                               <th>Maker</th>
                               <th>Type</th>
                               <th>Stock</th>
                               <th>Quantity</th>
                           </tr>
                       </thead>
                       <tbody id="tbody_logistic_equipment">
                           <?php foreach ($logistic_equipments as $logistic_equipment): ?>
                               <tr>
                                   <td width="5">
                                       <input type="checkbox" class="flat-red check" name="id[]" value="<?= $logistic_equipment->id_logistic_equipment; ?>">
                                   </td>
                                   <td><?= _ent($logistic_equipment->logistic_equipment_name); ?></td>
                                   <td><?= _ent($logistic_equipment->logistic_maker); ?></td>
                                   <td><?= _ent($logistic_equipment->logistic_equipment_type); ?></td>
                                   <td>
                                       <input class="classQty" type="hidden" value="<?= $logistic_equipment->quantity; ?>"/><?= _ent($logistic_equipment->quantity); ?>
                                   </td> 
                                   <td style="background-color: #FFD200"><div class="in-selection" id="input_qty" contenteditable="false"></div></td>
                               </tr>
                           <?php endforeach; ?>
                           <?php if ($logistic_equipment_counts == 0) : ?>
                               <tr>
                                   <td colspan="100">
                                       Logistic Equipment data is not available
                                   </td>
                               </tr>
                           <?php endif; ?>
                       </tbody>
                   </table>
               </div>
               
               <div class="form-group">

                   <button class="btn btn-flat btn-primary btn_add_new btn_action btn-danger" id="btn_insert" data-stype='stay' title="Insert">
                       <i class="fa fa-check" ></i> Insert
                   </button>

                   <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                       <i class="fa fa-save" ></i> <?= cclang('save_button'); ?>
                   </button>

                   <a class="btn btn-flat btn-default btn_action" id="btn_cancel" title="<?= cclang('cancel_button'); ?> (Ctrl+x)">
                       <i class="fa fa-undo" ></i> <?= cclang('cancel_button'); ?>
                   </a>
                   <span class="loading loading-hide">
                       <img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> 
                       <i><?= cclang('loading_saving_data'); ?></i>
                   </span>
               </div>   
               
               <div class="table-responsive"> 

                   <i>Selected</i>    
                   <table class="table table-bordered table-striped dataTable">
                       <thead>
                           <tr class="">
                               <th>Name</th>
                               <th>Maker</th>
                               <th>Type</th>
                               <th>Quantity</th>
                           </tr>
                       </thead>
                       <tbody id="tbody_logistic_equipment">

                           <tr>

                               <td id="in_name"></td>

                               <td id="in_maker"></td>

                               <td id="in_type"></td>

                               <td id="in_quantity"></td>

                           </tr>


                       </tbody>
                   </table>
               </div>
                  
               </div>
               
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_logistic_equipment').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/logistic_equipment/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/
    
    var checkboxes = new Array();
    checkboxes = $('input.check');
    
    var arr = new Array();
    arr = $('.classQty');
    
    checkboxes.on('ifChecked ifUnchecked',function(event){
       
        if(event.type==='ifChecked'){
            $('.in-selection').attr('contenteditable', 'true');                  
            var chkArray = [];   
            chkArray.push($(this).val());  
            console.log('print -> Arr::'  + arr.length); 
            
            for(var i=0 ; i< chkArray.length ; i++){
                console.log('check array[] ::' + chkArray[i]);
            }  
            for(var i=0 ; i< arr.length ; i++){
                console.log('print -> Arr Values ::'  + arr[i].values); 
                
            }  
            
                 
        }
          
    });

    

  }); /*end doc ready*/
</script>