<html>
     <style type="text/css">
        .col-sm-8 {
          margin-left: 70px;  
          padding-top: 5px;
          background-color:#e3e3e3;
        }
    </style>
</html>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Logistic Sparepart      <small><?= cclang('detail', ['Logistic Sparepart']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/logistic_sparepart'); ?>">Logistic Sparepart</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Logistic Sparepart</h3>
                     <h5 class="widget-user-desc">Detail Logistic Sparepart</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_logistic_sparepart" id="form_logistic_sparepart" >
                   
<!--                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Logistic Sparepart </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->id_logistic_sparepart); ?>
                        </div>
                    </div>-->
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Equipment Name </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->logistic_sparepart_equipment_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Equipment Maker </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->logistic_sparepart_equipment_maker); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Equipment Type </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->logistic_sparepart_equipment_type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Name </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->logistic_sparepart_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Type </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->logistic_sparepart_type); ?>
                        </div>
                    </div>
                                         
                   <!--  <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Part Number </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->logistic_sparepart_part_number); ?>
                        </div>
                    </div> -->
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Price </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->price); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Unit </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->unit); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Quantity </label>

                        <div class="col-sm-8">
                           <?= _ent($logistic_sparepart->quantity); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('logistic_sparepart_update', function() use ($logistic_sparepart){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit logistic_sparepart (Ctrl+e)" href="<?= site_url('administrator/logistic_sparepart/edit/'.$logistic_sparepart->id_logistic_sparepart); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Logistic Sparepart']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/logistic_sparepart/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Logistic Sparepart']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
