<html>
     <style type="text/css">
        .col-sm-8 {
          margin-left: 70px;  
          padding-top: 5px;
          background-color:#e3e3e3;
        }
    </style>
   
</html>


<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}

//jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Company      <small><?= cclang('detail', ['Company']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/company'); ?>">Company</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Company</h3>
                     <h5 class="widget-user-desc">Detail Company</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_company" id="form_company" >
                   
<!--                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Company </label>

                        <div class="col-sm-8">
                           <?= _ent($company->id_company); ?>
                        </div>
                    </div>-->
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Name </label>
                         
                        <div class="col-sm-8">
                           <?= _ent($company->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Owner </label>

                        <div class="col-sm-8">
                           <?= _ent($company->owner); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Address </label>

                        <div class="col-sm-8">
                           <?= _ent($company->address); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($company->email); ?>
                        </div>
                    </div>
					
					<div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NPWP </label>

                        <div class="col-sm-8">
                           <?= _ent($company->npwp); ?>
                        </div>
                    </div>
					
					<div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Telepon </label>

                        <div class="col-sm-8">
                           <?= _ent($company->telepon); ?>
                        </div>
                    </div>
                          

					<div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Fax </label>

                        <div class="col-sm-8">
                           <?= _ent($company->fax); ?>
                        </div>
                    </div>
						  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Contract </label>

                        <div class="col-sm-8">
                           <?= _ent($company->contract_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Territory </label>

                        <div class="col-sm-8">
                           <?= _ent($company->territory_name); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('company_update', function() use ($company){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit company (Ctrl+e)" href="<?= site_url('administrator/company/edit/'.$company->id_company); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Company']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/company/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Company']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
