<html>
     <style type="text/css">
        .col-sm-8 {
          margin-left: 70px;  
          padding-top: 5px;
          background-color:#e3e3e3;
        }
    </style>
   
</html>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Ship Equipment      <small><?= cclang('detail', ['Ship Equipment']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/ship_equipment'); ?>">Ship Equipment</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Ship Equipment</h3>
                     <h5 class="widget-user-desc">Detail Ship Equipment</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_ship_equipment" id="form_ship_equipment" >
                   
<!--                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Equipment </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->id_equipment); ?>
                        </div>
                    </div>-->
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Company </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ship Name </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->ship_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Name </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->logistic_equipment_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Maker </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->maker); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Type </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Serial Number </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->serial_number); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Manufacture Date </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->manufacture_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Beacon </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->beacon); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Battery </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->battery); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Hru </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->hru); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Magnetron </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->magnetron); ?>
                        </div>
                    </div>
                    
                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UPS Battery </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->ups_battery); ?>
                        </div>
                    </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Emergency Battery </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->emergency_battery); ?>
                        </div>
                    </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Annual Test </label>

                        <div class="col-sm-8">
                           <?= _ent($ship_equipment->annual_test); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('ship_equipment_update', function() use ($ship_equipment){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit ship_equipment (Ctrl+e)" href="<?= site_url('administrator/ship_equipment/edit/'.$ship_equipment->id_equipment); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Ship Equipment']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/ship_equipment/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Ship Equipment']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
