<html>
     <style type="text/css">
        .col-sm-8 {
          margin-left: 70px;  
          padding-top: 5px;
          background-color:#e3e3e3;
        }
    </style>
   
</html>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Ship      <small><?= cclang('detail', ['Ship']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/ship'); ?>">Ship</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Ship</h3>
                     <h5 class="widget-user-desc">Detail Ship</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_ship" id="form_ship" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Ship </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->id_ship); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Company </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pic </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->pic); ?>
                        </div>
                    </div>
					
					<div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pic Email</label>

                        <div class="col-sm-8">
                           <?= _ent($ship->pic_email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Contact Number </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->contact_number); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ship Name </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->ship_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ship Type </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->ship_type_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Management Company </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->management_company); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Groos Ton </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->groos_ton); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Class </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->class); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Flag </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->flag); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Imo </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->imo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Mmsi </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->mmsi); ?>
                        </div>
                    </div>
                      
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Annual Survey </label>

                        <div class="col-sm-8">
                           <?= _ent($ship->annual_survey); ?>
                        </div>
                    </div>  
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('ship_update', function() use ($ship){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit ship (Ctrl+e)" href="<?= site_url('administrator/ship/edit/'.$ship->id_ship); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Ship']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/ship/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Ship']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
